CREATE TABLE heroes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    atributo VARCHAR(30) NOT NULL,
    imagen_url TEXT,
    slug VARCHAR(250) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE cofres_cache (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    anio INTEGER NOT NULL,
    sigla VARCHAR(10) NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    imagen_url TEXT,
    slug VARCHAR(250) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE item (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    heroe_id BIGINT NOT NULL,
    cofre_id BIGINT NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    precio NUMERIC(10,2),
    slug VARCHAR(250) NOT NULL UNIQUE,
    imagen_url text not null,
    estado SMALLINT NOT NULL DEFAULT 1, -- 0 inactivo , 1 activo, 2 agotado
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE galeria_item (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    orden INTEGER NOT NULL DEFAULT 1,
    tipo SMALLINT NOT NULL DEFAULT 1, -- 1  set cache , 2 ventas
    imagen_url TEXT NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ventas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMPTZ NOT NULL,
    item_id BIGINT NOT NULL,
    precio NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
